export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_ERROR = 'GET_INGREDIENTS_ERROR';

export const INGREDIENTS_ADD = 'INGREDIENTS_ADD';
export const INGREDIENTS_REMOVE = 'INGREDIENTS_REMOVE';
