export const SET_ACTIVE_TAB_SCROLL = 'SET_ACTIVE_TAB'; 
export const SET_ACTIVE_TAB_CLICK = 'SET_ACTIVE_TAB_CLICK'; 
export const ADD_ITEMS_TITLE = 'ADD_ITEMS_TITLE'; 
export const ADD_ITEMS_REF = 'ADD_ITEMS_REF'